version: '3.3'

services:
  frontend:
    build:
      context: ./svelteproject  # Path to svelteproject folder
    ports:
      - "5555:5555"  # Ensure that this is exposed
  
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
