version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - shared_network  # Use shared network

networks:
  shared_network:
    external: true  # Use external to keep it consistent
