version: '3.3'

services:
  app:
    build:
      context: .  # This assumes your Dockerfile is in the root directory
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
