version: '3.3'

services:
  app:
    build:
      context: .  # Set context to the current directory (backend)
      dockerfile: Dockerfile  # Dockerfile is in the backend folder
    ports:
      - "5000:5000"
    networks:
      - shared_network  # Use shared network
    restart: unless-stopped  # Ensure container restarts if stopped

networks:
  shared_network:
    external: true  # Use external network
