name: container_up

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI

jobs:
  container_up:
    runs-on: self-hosted  # Specify your self-hosted runner here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: docker-compose -f /home/actions-runner/_work/Website-fullstack/Website-fullstack/docker-compose.yml up -d
