name: Deploy Node Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Docker Image
        run: |
          # Ensure we're in the root directory, not the frontend directory
          cd frontend  # Navigate to the frontend folder

          # Run docker-compose from the correct location (assuming it's in the root directory)
          docker-compose -f ../docker-compose.yml up -d --build  # Ensure the correct path to the docker-compose.yml file

      # Optionally clean up after deployment
      # - name: Clean up
      #   run: docker-compose -f ../docker-compose.yml down


