name: Deploy Node Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Docker Image
        run: |
          # Navigate to the frontend folder
          cd frontend  # Ensure we are in the frontend directory
          
          # Run docker-compose using the full path to the docker-compose.yml file in the root directory
          docker-compose -f docker-compose.yml up -d --build  # Correct path to docker-compose.yml

      # Optionally clean up after deployment
      # - name: Clean up
      #   run: docker-compose -f ../docker-compose.yml down
