name: Deploy Node Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: davidserver  # Use self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Create external network (shared_network)
        run: |
          docker network create shared_network || echo "Network already exists"
          
      - name: Build and Push Docker Image
        run: |
          # Run docker-compose from the frontend directory where docker-compose.yml is located
          docker-compose -f frontend/docker-compose.yml up -d --build  

      # Optionally clean up after deployment
      # - name: Clean up
      #   run: docker-compose -f frontend/docker-compose.yml down
