name: Deploy Node Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: davidserver  # Use self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Docker Image
        run: |
          # Run docker-compose directly from the 'frontend' folder
          docker-compose -f frontend/docker-compose.yml up -d --build  # Updated to reference docker-compose.yml in the frontend folder


      # Optionally clean up after deployment
      # - name: Clean up
      #   run: docker-compose -f ../docker-compose.yml downname: Deploy Node Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: davidserver  # Use self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Docker Image
        run: |
          # Ensure we're in the frontend directory where docker-compose.yml is
          cd frontend  # Navigate to the frontend folder

          # Run docker-compose from the current location
          docker-compose up -d --build  # Build and run the containers

      # Optionally clean up after deployment
      # - name: Clean up
      #   run: docker-compose down



