name: docker_compose_up_runner

on:
#  push:
#    branches:
#      - main
#      - stage
  workflow_dispatch:

jobs:
  docker_compose_up_runner:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and Push Docker Image
        run: |
          docker-compose -f docker-compose.yml up -d --build
#      - name: Clean up
#       run: docker-compose -f docker-compose.yml down
