name: Deploy Fullstack Application

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: self-hosted  # Use self-hosted runner (make sure 'davidserver' is registered)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # 🔹 Update from v2 to v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 🔹 Update from v1 to v2

      - name: Create external network (WebsiteFullstackNetwork)
        run: |
          docker network create WebsiteFullstackNetwork || echo "Network already exists"

      - name: Set up Environment Variables
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          
      - name: Build and Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
