name: Deploy Nginx Proxy Manager

on:
  workflow_dispatch:

jobs:
  deploy_nginx_proxy_manager:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Start Nginx Proxy Manager with Specific Compose File
        run: |
          docker-compose -f docker-compose.nginx.yml up -d --build
          
      - name: Confirm Nginx Proxy Manager Deployment
        run: |
          docker ps | grep jc21/nginx-proxy-manager || echo "Nginx Proxy Manager is not running"
