name: Deploy Nginx Proxy Manager

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  deploy-nginx-proxy-manager:
    runs-on: self-hosted  # Specify your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if Nginx Proxy Manager is running
        run: |
          docker ps | grep jc21/nginx-proxy-manager || echo "Nginx Proxy Manager is not running"

      - name: Navigate to nginx_prox_manager folder and deploy Nginx Proxy Manager
        run: |
          cd /home/actions-runner/_work/Website_fullstack/Website_fullstack/nginx_prox_manager
          docker-compose up -d  # Start the container in detached mode

      - name: Verify Nginx Proxy Manager is running
        run: |
          docker ps -f name=nginx-proxy-manager  # Check if Nginx Proxy Manager is up and running
